### ISSUE TITLE
Support for removing labels as well?

### ISSUE THREAD

**Issue by derryl** [banyan/auto-label#4]
We have a workflow on our team where PR's are initially marked `Needs Review` (when work has been completed, and it's ready for a final approval)

Your action works very well for applying the `Review Approved` label once the min. number of approvals have been met. It would be nice to also remove the `Needs Review` label at that point!

Thanks for creating this action 👍

**Comment by banyan** [comment]
sorry for late replay. I think https://github.com/pullreminders/label-when-approved-action would suit in that case.
